kibalabs/core-js

.github/pull_request_template.md
package-lock.json
package.json

Feature - update package metadata + dependencies

---

package-lock.json
package.json
src/util/classNameUtil.ts
src/util/dateUtil.ts

Fix - small updates for typing

---

.github/workflows/deploy.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
package-lock.json
package.json
src/requester/request.ts
src/requester/requester.ts
src/requester/response.ts
src/services/serviceClient.ts
src/util/browserUtil.ts
src/util/classNameUtil.ts
src/util/dateUtil.ts
src/util/fileUtil.ts
src/util/objectUtil.ts
src/util/promiseUtil.ts
src/util/serializationUtil.ts
src/util/stringUtil.ts
src/util/typeUtil.ts

Feature - update CI to include next version deployment + linting + type-checking

---

package.json

Fix - add publish-next script

---

.github/workflows/deploy.yml
package-lock.json
package.json
src/requester/requester.ts
src/services/serviceClient.ts

The endpoints are badly typed, discovered due to https://github.com/kibalabs/everypage/pull/4/files

Fix - update ServiceClient typing

---

package-lock.json
package.json
src/requester/requester.ts
src/util/stringUtil.ts

Fix: set content-type if not set in requester

---

.npmrc
package-lock.json
package.json

Feature: update to latest build-js

---

.github/pull_request_template.md

Feature: update pull_request_template

---

src/requester/requester.ts

Fix: dont set content-type header for formdata requests

---

src/requester/requester.ts

Fix: remove undefined before converting GET request data to query params

---

src/util/browserUtil.ts
src/util/stringUtil.ts
src/util/urlUtils.ts

Add browserUtil, stringUtil and urlUtil from mdtp

Feature: Add browserUtil, stringUtil and urlUtil from mdtp

---

src/util/index.ts

Export urlUtils in the index file.

Fix: export urlUtil

---

package-lock.json
package.json
src/util/browserUtil.ts
src/util/fileUtil.ts

Feature: improveme browserUtil for SSR + add copyFileSync and copyDirectorySync to fileUtil

---

src/util/numberUtil.ts

Fix: replace numberUtil.numberWithCommas to not use regex lookbehind

---

package-lock.json
package.json
src/util/asyncUtil.ts

Fiddle: update dependencies

---

package-lock.json
package.json
src/util/chainUtil.ts
src/util/index.ts
src/util/numberUtil.ts
src/util/stringUtil.ts
src/util/urlUtils.ts

Add utils from tokenhunt and tokengallery

KIBA-1482: Add utils

---

src/util/dateUtil.ts

KIBA-1499: Add dateToRelativeString and dateToRelativeShortString to dateUtil

---

CHANGELOG.md

This is required to know what notable changes have been made between each release

KIBA-1504: Add CHANGELOG

---

CHANGELOG.md
src/requester/requester.ts
src/util/urlUtils.ts

Feature: added createSearchParams to urlUtil

---

CHANGELOG.md
package-lock.json
package.json
src/util/chainUtil.ts
src/util/dateUtil.ts
src/util/listUtil.ts
src/util/numberUtil.ts
src/util/stringUtil.ts

Major: Update chainUtil to use BigInt instead of BigNumber + add more utils

---

package.json

Fix: update files used in package

---

package.json

Fix: another try to fix package files

---

CHANGELOG.md
Dockerfile
makefile
package-lock.json
package.json
src/util/dateUtil.ts
src/util/objectUtil.ts

Fiddle: build with rolldown

---

Dockerfile
package-lock.json
package.json

Fix: use latest build to fix package

---

package-lock.json
package.json

Fix: update build for types

---

CHANGELOG.md
src/services/serviceClient.ts

Fiddle: add additionalHeaders to ServiceClient.makeRequest
